import { dirname } from "path";
import { fileURLToPath } from "url";
import { FlatCompat } from "@eslint/eslintrc";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({
  baseDirectory: __dirname,
});

const eslintConfig = [
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    ignores: [
      "next-env.d.ts", // Auto-generated by Next.js — uses triple-slash references by design
      ".next/**", // Next.js build output
      "node_modules/**",
    ],
  },
];

export default eslintConfig;
